version: "3.8"

services:
  frontend:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: .
      dockerfile: front/Dockerfile
      target: development
    volumes:
      - ./front/src/:/app/front/src/
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - arena-facil-frontend.apps.internal